# Project 4 -- Vinay Gannamaneni

**TA Help:** (for instance) John Smith, Alice Jones, etc., list names of any TAs who helped you

- For example: Help with figuring out how to write a function (describe the tasks that they helped you with)

**Collaboration:** My Friend in CS, My Uncle, Another Student, etc., list names of any other people who helped you

(describe the tasks that they helped you with)
- For example: helped figuring out how to load the dataset.
- Another example: helped debug error with my plot.

**Internet Resources:** Stack Exchange, Stack Overflow, etc.

(describe any information that you learned from internet resources, including the URLs)
- data frames in Pandas versus R from StackOverflow  https://stackoverflow.com/questions/8991709/why-were-pandas-merges-in-python-faster-than-data-table-merges-in-r-in-2012

**ChatGPT, Gemini, Claude, etc:** Any language models or generative AI chatbots that helped you.

(if you used any such tools, please tell us here)
- For example:  I asked ChatGPT how to define a new data frames
- Another example:  Gemini told me how to make a function for sorting my data

- ***Link to AI Chat History***: Please share a link to your chat if you used AI (ex. ChatGPT Shared Links)
**OVERALL MESSAGE:** Any time that you used anything except your brain to solve the questions in these projects, you need to disclose such resources at the start of the project, with details about your usage of the tools.

**YOUR OWN WORK:** Even when you utilize other resources, do NOT just copy and paste.  Write all explanations in your own words, using several sentences in English, which are understandable and which you wrote (and did not just copy and paste).

## Loading Titanic data and comparing lists vs DataFrame columns

In [1]:
import pandas as pd
myDF = pd.read_csv('/anvil/projects/tdm/data/titanic/titanic.csv')

In [2]:
myDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

This shows the column names, data types, and non-null counts. We can see columns like Survived, Pclass, Name, Sex, Age, etc.

In [3]:
myDF.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

This shows statistical summaries (mean, min, max, etc.) for numeric columns.

In [4]:
my_names = list(myDF['Name'])
my_ages = list(myDF['Age'])
combined = list(my_names) + list(my_ages)

This converts the Age & Name column to a list and combines them.

In [7]:
combined[:10]

['Braund, Mr. Owen Harris',
 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
 'Heikkinen, Miss. Laina',
 'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
 'Allen, Mr. William Henry',
 'Moran, Mr. James',
 'McCarthy, Mr. Timothy J',
 'Palsson, Master. Gosta Leonard',
 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
 'Nasser, Mrs. Nicholas (Adele Achem)']

In [9]:
small_df = myDF[['Name', 'Age']]
small_df.shape

(891, 2)

Using double brackets selects multiple columns to create a smaller dataset

## Comparing types and filtering passengers under 20

In [13]:
my_names[44]

'Devaney, Miss. Margaret Delia'

In [12]:
my_ages[44]

19.0

This shows the name and age of the 45th passenger.

In [14]:
type(my_names)

list

In [15]:
myDF['Name'].dtype

dtype('O')

In the original dataframe this shows 'O' - which stores strings.

In [16]:
type(my_ages)

list

In [17]:
myDF['Age'].dtype

dtype('float64')

In the original dataframe this shows 'float64' - which stores decimal numbers.

In [18]:
myDF['Age'][myDF['Age'] < 20]

7       2.0
9      14.0
10      4.0
14     14.0
16      2.0
       ...
855    18.0
869     4.0
875    15.0
877    19.0
887    19.0
Name: Age, Length: 164, dtype: float64

This filters to show only ages under 20 and NA values are automatically excluded.

In [19]:
myDF['Name'][myDF['Age'] < 20]

7            Palsson, Master. Gosta Leonard
9       Nasser, Mrs. Nicholas (Adele Achem)
10          Sandstrom, Miss. Marguerite Rut
14     Vestrom, Miss. Hulda Amanda Adolfina
16                     Rice, Master. Eugene
                       ...
855              Aks, Mrs. Sam (Leah Rosen)
869         Johnson, Master. Harold Theodor
875        Najib, Miss. Adele Kiamie "Jane"
877                    Petroff, Mr. Nedelio
887            Graham, Miss. Margaret Edith
Name: Name, Length: 164, dtype: object

This shows the names of passengers under 20 years old.

In [25]:
my_selection = myDF['Age'] < 20
my_result = myDF['Name'][my_selection] + ", age " + myDF['Age'][my_selection].astype(str)

This creates a boolean series (True/False values) and ``.astype(str)`` converts ages to strings so we can concatenate them.

In [26]:
my_result

7             Palsson, Master. Gosta Leonard, age 2.0
9       Nasser, Mrs. Nicholas (Adele Achem), age 14.0
10           Sandstrom, Miss. Marguerite Rut, age 4.0
14     Vestrom, Miss. Hulda Amanda Adolfina, age 14.0
16                      Rice, Master. Eugene, age 2.0
                            ...
855              Aks, Mrs. Sam (Leah Rosen), age 18.0
869          Johnson, Master. Harold Theodor, age 4.0
875        Najib, Miss. Adele Kiamie "Jane", age 15.0
877                    Petroff, Mr. Nedelio, age 19.0
887            Graham, Miss. Margaret Edith, age 19.0
Length: 164, dtype: object

This shows all passengers under 20 with their names and ages.

## Recoding survival into categories and combining with sex

In [27]:
myDF["Status"] = pd.Categorical(
    myDF["Survived"],
    categories=[0, 1],
    ordered=True
).rename_categories(["Dead", "Alive"])

This converts 0 to "Dead" and 1 to "Alive". The ``ordered=True`` preserves this as an ordered category.

In [28]:
myDF['Status'].value_counts()

Status
Dead     549
Alive    342
Name: count, dtype: int64

This shows us how many passengers were Dead vs Alive.

In [29]:
myDF["Combined"] = myDF["Status"].astype(str).str.cat(myDF["Sex"], sep=", ")

``.str.cat()`` combines the two columns with ", " as separator.

In [30]:
myDF['Combined'].value_counts()

Combined
Dead, male       468
Alive, female    233
Alive, male      109
Dead, female      81
Name: count, dtype: int64

I used ``pd.Categorical`` with 'rename_categories' to create the Status column. This method preserves the ordered nature of the categories.

## Exploring the age range and identifying older passengers

In [31]:
myDF['Age'].value_counts()

Age
24.00    30
22.00    27
18.00    26
28.00    25
30.00    25
         ..
24.50     1
0.67      1
0.42      1
34.50     1
74.00     1
Name: count, Length: 88, dtype: int64

This shows all unique ages and their frequencies. To find the youngest and oldest passenger,

In [32]:
myDF['Age'].min()

0.42

In [33]:
myDF['Age'].max()

80.0

In [35]:
old_ages = [61, 62, 63, 64, 65, 66, 70, 70.5, 71, 74, 80]
old = myDF["Age"][myDF["Age"].isin(old_ages)]

This list contains ages we consider "old" (61-80 range).

``.isin()`` checks if each Age value is in the 'old_ages' list. This returns only the matching ages from the dataframe.

In [36]:
old.value_counts()

Age
62.0    4
61.0    3
65.0    3
70.0    2
71.0    2
63.0    2
64.0    2
66.0    1
70.5    1
80.0    1
74.0    1
Name: count, dtype: int64

In [38]:
my_list1 = myDF["Age"][myDF["Age"] <= 10]
my_list1

7      2.00
10     4.00
16     2.00
24     8.00
43     3.00
       ...
827    1.00
831    0.83
850    4.00
852    9.00
869    4.00
Name: Age, Length: 64, dtype: float64

This filters for ages 10 and under.

In [39]:
my_list2 = myDF["Age"][(myDF["Age"] > 10) & (myDF["Age"] <= 60)]

This filters for ages between 10 and 60. The ``&`` operator combines the two conditions.

In [41]:
people = list(my_list1) + list(my_list2)
len(people)

692

Combined 'my_list1' and 'my_list2' to create people to show the length

## Grouping passengers into age brackets and cross tabulating with survival status

In [42]:
children = myDF["Age"][myDF["Age"] <= 20]
children.value_counts()

Age
18.00    26
19.00    25
16.00    17
20.00    15
17.00    13
2.00     10
4.00     10
9.00      8
1.00      7
14.00     6
3.00      6
15.00     5
5.00      4
8.00      4
11.00     4
7.00      3
6.00      3
0.83      2
0.75      2
10.00     2
13.00     2
14.50     1
12.00     1
0.92      1
0.67      1
0.42      1
Name: count, dtype: int64

This contains all ages 20 and under and shows the distrubution of children's ages

In [43]:
print("Children min:", children.min())
print("Children max:", children.max())

Children min: 0.42
Children max: 20.0

Confirms the range is correct

In [44]:
young = myDF["Age"][(myDF["Age"] > 20) & (myDF["Age"] <= 40)]
young.value_counts()

Age
24.0    30
22.0    27
30.0    25
28.0    25
21.0    24
25.0    23
36.0    22
29.0    20
26.0    18
35.0    18
27.0    18
32.0    18
31.0    17
23.0    15
33.0    15
34.0    15
39.0    14
40.0    13
38.0    11
37.0     6
28.5     2
32.5     2
30.5     2
36.5     1
20.5     1
23.5     1
24.5     1
34.5     1
Name: count, dtype: int64

This contains ages from 21 to 40.

In [45]:
print("Young min:", young.min())
print("Young max:", young.max())

Young min: 20.5
Young max: 40.0

Confirms the range is 21-40.

In [46]:
adult = myDF["Age"][(myDF["Age"] > 40) & (myDF["Age"] <= 60)]
adult.value_counts()

Age
42.0    13
45.0    12
50.0    10
48.0     9
44.0     9
47.0     9
54.0     8
51.0     7
41.0     6
52.0     6
49.0     6
58.0     5
43.0     5
60.0     4
56.0     4
46.0     3
55.0     2
59.0     2
40.5     2
57.0     2
45.5     2
55.5     1
53.0     1
Name: count, dtype: int64

In [47]:
print("Adult min:", adult.min())
print("Adult max:", adult.max())

Adult min: 40.5
Adult max: 60.0

Confirms the range is 41-60.

Old was already created in Question 4 as ages 61-80

In [48]:
myDF.loc[myDF["Age"].isin(children), "AgeGroup"] = "Children"

Assigns "Children" label to ages in children list

``.loc[]`` allows us to assign values to specific rows. ``.isin()`` checks if Age values are in the children list.

In [50]:
myDF.loc[myDF["Age"].isin(young), "AgeGroup"] = "Young"

Assigns "Young" label to ages in young list

In [49]:
myDF.loc[myDF["Age"].isin(adult), "AgeGroup"] = "Adult"

Assigns "Adult" label to ages in adult list

In [51]:
myDF.loc[myDF["Age"].isin(old), "AgeGroup"] = "Old"

Assign "Old" label to ages in old list

In [52]:
myDF['AgeGroup'].value_counts()

AgeGroup
Young       385
Children    179
Adult       128
Old          22
Name: count, dtype: int64

This shows how many passengers are in each age group.

In [53]:
pd.crosstab(myDF['AgeGroup'], myDF['Combined'])

Combined  Alive, female  Alive, male  Dead, female  Dead, male
AgeGroup
Adult                34           16            11          67
Children             53           29            24          73
Old                   3            2             0          17
Young               107           46            29         203

Create a cross tabulation comparing AgeGroup and Combined

This creates a table showing the relationship between age groups and the combined status/sex categories (e.g., "Alive, female").Each cell shows the count of passengers in that combination.

## Pledge

By submitting this work I hereby pledge that this is my own, personal work. I've acknowledged in the designated place at the top of this file all sources that I used to complete said work, including but not limited to: online resources, books, and electronic communications. I've noted all collaboration with fellow students and/or TA's. I did not copy or plagiarize another's work.

> As a Boilermaker pursuing academic excellence, I pledge to be honest and true in all that I do. Accountable together – We are Purdue.

https://www.purdue.edu/odos/osrr/honor-pledge/